### ISSUE TITLE
Make channelID configurable for RoundAlertAC function

### ISSUE THREAD

**Issue by baiyuchen1228** [HaKkaz/LeetCode-Alert-bot#6]
## Issue Description

Currently, the `RoundAlertAC` function in the Discord bot code has a hardcoded `channelID`:

```go
func RoundAlertAC(s *discordgo.Session, timeSlot time.Duration) error {
    channelID := "1153931585230491658"

    tracedUsers, err := readTracedList()
    if err != nil {
        return err
    }

    // Rest of the function...
}
```

This hardcoded channelID makes it inflexible to use the bot in different channels or servers.

**Comment by HaKkaz** [comment]
Thanks for your advice. I have already updated the feature.
